---
- name: make filesystem for the new block device
  become: true
  filesystem:
    fstype: ext4
    dev: /dev/{{ blk_device_name }}

- name: creating directory in block device
  become: true
  file: 
    path: /mnt/data
    state: directory

- name: mounting new directory in block device
  become: true
  mount: 
    path: /data/
    src: /dev/{{ blk_device_name }}
    fstype: ext4
    state: mounted

- name: creating hdfs directory
  become: true
  file:
    path: /data/hdfs
    state: directory
    mode: 0777

- name: creating spark directory
  become: true
  file:
    path: /data/spark
    state: directory
    mode: 0777