---
- name: uploading docker files for flask_app
  become: false
  copy:
    src: .
    dest: /tmp/flask_app/

- name: build flask_app docker image
  command: docker build -t flask_app_image .
  args:
    chdir: /tmp/flask_app

- name: run flask_app docker container
  command: docker container run -p 5000:5000 -d --network=nginx_network --rm --name flask_app_container flask_app_image
  args:
    chdir: /tmp/flask_app
