version: '3.3'

services:
   nginx-service:
     build: ./nginx
     restart: always
     ports:
      - 80:80
     image: nginx_image
     container_name: nginx_service
     networks:
      - network
     
networks:
  network: