---
- hosts: remote_machines
  become: false

  tasks:
    - name: Updating all packages to the latest version
      become: true
      apt:
        upgrade: dist
        update_cache: yes

    - name: Installing apt packages
      become: true
      apt: 
        name: 
          - python3-tk
          - python3-pip
          - python3-venv
          - python-virtualenv
        state: latest 
        update_cache: yes
        autoremove: yes
        autoclean: yes

    - name: Installing pip packages in virtualenv
      become: false
      pip: 
        name: 
          - flask
          - jupyter
          - scikit-learn
          - pandas
          - numpy
          - scipy
          - matplotlib
          - seaborn
        state: latest
        virtualenv: /home/ubuntu/venvs/da_env
        virtualenv_python: python3.5
        virtualenv_site_packages: no
